name: React CD
on:
    push:
      branches: [ main ]

jobs:
    deliver:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar o repositório
              uses: actions/checkout@v4

            - name: Simulando CD
              uses: actions/upload-artifact@v4  
              with:
                name: projeto.zip
                path: .

            
