name: React CD
on:
    push:
      branches: [ main ]

jobs:
    deliver:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar o repositório
              uses: actions/checkout@v4

            - name: Build do React
              run: |
               npm install
               npm run build

            - name: Build do Docker
              run: docker build -t projeto .

            - name: Simulando CD
              uses: actions/upload-artifact@v4  
              with:
                name: projeto.zip
                path: .

    deploy:
        runs-on: ubuntu-latest
        needs: deliver
        steps:
          - name: Download do artefato
            uses: actions/download-artifact@v4
            with:
             name: projeto.zip
  
          - name: Verificar Dockerfile e arquivos
            run: ls -R
  
          - name: Simulando deploy com Docker
            run: echo "Deploy com Docker pronto para usar em produção!"